import { jsPDF } from "jspdf";

export const downloadPDF = (result) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Helper for centering text
    const centerText = (text, y) => {
        const textWidth = doc.getStringUnitWidth(text) * doc.internal.getFontSize() / doc.internal.scaleFactor;
        const x = (pageWidth - textWidth) / 2;
        doc.text(text, x, y);
    };

    // Header
    doc.setFillColor(0, 0, 0); // Black background header
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    centerText("TRUESIGHT ANALYSIS REPORT", 25);

    // Metadata
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Report ID: ${result.timestamp}`, 20, 50);
    doc.text(`Date: ${new Date(result.timestamp).toLocaleString()}`, 20, 56);

    // Integrity Hash (Boxed)
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(20, 65, pageWidth - 40, 20, 3, 3, 'FD');

    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text("INTEGRITY HASH (SHA-256):", 25, 74);

    // We need to fetch the hash passed in or re-calculate it. 
    // For now, let's assume the hash is part of the result object or separate.
    // We'll wrap long text
    const hash = result.hash || "Not Available in Preview";
    doc.setFont("courier", "bold");
    doc.text(hash, 25, 80);

    // Verdict Section
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("VERDICT SUMMARY", 20, 105);

    // Score Circle logic (simplified as text for PDF)
    doc.setFontSize(40);
    const score = result.aggregateScore;
    let color = [0, 150, 255]; // Blue
    if (score >= 80) color = [0, 200, 100]; // Green
    else if (score < 50) color = [255, 50, 50]; // Red

    doc.setTextColor(...color);
    doc.text(`${score}%`, 20, 125);

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text("CREDIBILITY SCORE", 20, 132);

    // Key Insight
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "italic");

    // Simple check for insight
    const allFlags = [
        ...result.breakdown.linguistics.flags,
        ...result.breakdown.logic.flags,
        ...result.breakdown.source.flags
    ];
    const insight = allFlags.length > 0
        ? `Primary Concern: ${allFlags[0].type} - ${allFlags[0].description}`
        : "No significant anomalies detected. Content appears credible.";

    const splitInsight = doc.splitTextToSize(insight, pageWidth - 100);
    doc.text(splitInsight, 80, 120);

    // Breakdown Table-ish
    let y = 150;

    const drawSection = (title, flags) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(50, 50, 50);
        doc.text(title.toUpperCase(), 20, y);
        y += 8;

        if (flags.length === 0) {
            doc.setFont("helvetica", "italic");
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text("No issues found.", 25, y);
            y += 10;
        } else {
            flags.forEach(flag => {
                doc.setFont("helvetica", "bold");
                doc.setFontSize(10);
                doc.setTextColor(0, 0, 0);
                doc.text(`• ${flag.type}`, 25, y);
                y += 5;

                doc.setFont("helvetica", "normal");
                doc.setTextColor(80, 80, 80);
                const desc = doc.splitTextToSize(flag.description, pageWidth - 45);
                doc.text(desc, 30, y);
                y += (desc.length * 5) + 5;
            });
        }
        y += 5;
    };

    drawSection("Linguistics Analysis", result.breakdown.linguistics.flags);
    drawSection("Logic & Reasoning", result.breakdown.logic.flags);
    drawSection("Source Intelligence", result.breakdown.source.flags);

    // Footer
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 270, pageWidth - 20, 270);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by TrueSight AI • Immutable Analysis Record", 20, 276);

    doc.save(`TrueSight_Report_${result.timestamp}.pdf`);
};
